// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SQLplus.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Statics
{

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Class for Static Query: AddressTypesData
    /// </summary>
    public partial class StaticData
    {
        /// <summary>
        /// List for Data returned by Static Query: AddressTypesData
        /// </summary>
        public static List<AddressTypesData> AddressTypesDataList = new List<AddressTypesData>()
        {
            new AddressTypesData((byte)1, @"Residential", @"Residential", @"Residential Address"),
            new AddressTypesData((byte)2, @"Business", @"Business", @"Business Address"),
        };
    }

    /// <summary>
    /// Concrete class representation for Static Query: AddressTypesData
    /// </summary>
    public class AddressTypesData
    {
        #pragma warning disable 1591

        public AddressTypesData(byte AddressTypeId, string Name, string DisplayName, string Description)
        {
            this.AddressTypeId = AddressTypeId;
            this.Name = Name;
            this.DisplayName = DisplayName;
            this.Description = Description;
        }
        
        #pragma warning restore 1591

        /// <summary>
        /// Result for Column: AddressTypeId
        /// </summary>
        public byte AddressTypeId  { get; }

        /// <summary>
        /// Result for Column: Name
        /// </summary>
        public string Name  { get; }

        /// <summary>
        /// Result for Column: DisplayName
        /// </summary>
        public string DisplayName  { get; }

        /// <summary>
        /// Result for Column: Description
        /// </summary>
        public string Description  { get; }

    }
}