// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SQLplus.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Statics
{

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Class for Static Query: CustomerType
    /// </summary>
    public partial class StaticData
    {
        /// <summary>
        /// List for Data returned by Static Query: CustomerType
        /// </summary>
        public static List<CustomerType> CustomerTypeList = new List<CustomerType>()
        {
            new CustomerType((byte)1, @"Residential", @"Residential Customers"),
            new CustomerType((byte)2, @"Commercial", @"Commercial Customers"),
        };
    }

    /// <summary>
    /// Concrete class representation for Static Query: CustomerType
    /// </summary>
    public class CustomerType
    {
        #pragma warning disable 1591

        public CustomerType(byte CustomerTypeId, string Name, string Description)
        {
            this.CustomerTypeId = CustomerTypeId;
            this.Name = Name;
            this.Description = Description;
        }
        
        #pragma warning restore 1591

        /// <summary>
        /// Result for Column: CustomerTypeId
        /// </summary>
        public byte CustomerTypeId  { get; }

        /// <summary>
        /// Result for Column: Name
        /// </summary>
        public string Name  { get; }

        /// <summary>
        /// Result for Column: Description
        /// </summary>
        public string Description  { get; }

    }
}