// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSave
//     Last Modified On: 3/15/2023 7:54:50 PM
//     Written By: Author
//     Select Type: NonQuery
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Better.Models
{
    #nullable enable

    /// <summary>
    /// Output object for CustomerSave service.
    /// </summary>
    public partial class CustomerSaveOutput
    {

        #region Output Parameters

        /// <summary>
        /// Set to 0 for an insert, otherwise provide the customer id
        /// </summary>
        public int? CustomerId { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Actual return value for the routine.
        /// </summary>
        public int? ReturnValue { set; get; }

        #endregion Return Value
    }









}
