// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerInsert
//     Last Modified On: 3/12/2023 7:13:55 PM
//     Written By: Alan Hyneman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Sample.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerInsert service.
    /// </summary>
    public partial class CustomerInsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerInsertInput.
        /// </summary>
        public CustomerInsertInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerInsertInput.
        /// </summary>
        /// <param name="FirstName">Maps to parameter @FirstName.</param>
        /// <param name="LastName">Maps to parameter @LastName.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        public CustomerInsertInput(string? FirstName, string? LastName, string? Email)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Email = Email;
        }

        #endregion Constructors

        #region Fields

        private string? _FirstName;
        /// <summary>
        /// Maps to parameter @FirstName.
        /// </summary>
        public string? FirstName
        {
            get => _FirstName;
            set => _FirstName = value;
        }

        private string? _LastName;
        /// <summary>
        /// Maps to parameter @LastName.
        /// </summary>
        public string? LastName
        {
            get => _LastName;
            set => _LastName = value;
        }

        private string? _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        public string? Email
        {
            get => _Email;
            set => _Email = value;
        }

        #endregion

    }
}