// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerById
//     Last Modified On: 3/15/2023 7:28:20 PM
//     Written By: Alan@SQLPlus.net
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Better.Models
{
    #nullable enable

    /// <summary>
    /// Output object for CustomerById service.
    /// </summary>
    public partial class CustomerByIdOutput
    {

        #region Return Value

        /// <summary>
        /// Actual return value for the routine.
        /// </summary>
        public int? ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of CustomerByIdResult.
        /// </summary>
        public CustomerByIdResult? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for CustomerById service.
    /// </summary>




    public partial class CustomerByIdResult
	{
        /// <summary>
        /// Result set object for CustomerById.
        /// </summary>
        /// <param name="CustomerId">Maps to table value column CustomerId.</param>
        /// <param name="FirstName">Maps to table value column FirstName.</param>
        /// <param name="LastName">Maps to table value column LastName.</param>
        /// <param name="Email">Maps to table value column Email.</param>
        public CustomerByIdResult(int CustomerId, string FirstName, string LastName, string Email)
        {
             this.CustomerId = CustomerId;
             this.FirstName = FirstName;
             this.LastName = LastName;
             this.Email = Email;
        }


        /// <summary>
        /// Maps to table value column CustomerId.
        /// </summary>
        public int CustomerId { set; get; }

        /// <summary>
        /// Maps to table value column FirstName.
        /// </summary>
        public string FirstName { set; get; }

        /// <summary>
        /// Maps to table value column LastName.
        /// </summary>
        public string LastName { set; get; }

        /// <summary>
        /// Maps to table value column Email.
        /// </summary>
        public string Email { set; get; }
    }


    #endregion Result Set Objects

}
