// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerQuery
//     Last Modified On: 3/1/2023 11:10:06 PM
//     Written By: Alan@SQLPlus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Better.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerQuery service.
    /// </summary>
    public partial class CustomerQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerQueryInput.
        /// </summary>
        public CustomerQueryInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerQueryInput.
        /// </summary>
        /// <param name="FirstName">Maps to parameter @FirstName.</param>
        /// <param name="LastName">Maps to parameter @LastName.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        public CustomerQueryInput(string? FirstName, string? LastName, string? Email)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Email = Email;
        }

        #endregion Constructors

        #region Fields

        private string? _FirstName;
        /// <summary>
        /// Maps to parameter @FirstName.
        /// </summary>
        public string? FirstName
        {
            get => _FirstName;
            set => _FirstName = value;
        }

        private string? _LastName;
        /// <summary>
        /// Maps to parameter @LastName.
        /// </summary>
        public string? LastName
        {
            get => _LastName;
            set => _LastName = value;
        }

        private string? _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        public string? Email
        {
            get => _Email;
            set => _Email = value;
        }

        #endregion

    }
}