// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL Plus Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SqlPlus.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SqlPlusBase
{
    #region usings
    
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    #region ValidInput

    /// <summary>
    /// Services as the base class for all input models.
    /// </summary>
    public abstract partial class ValidInput
    {
        /// <summary>
        /// List of ValidationResults populated during IsValid() call.
        /// </summary>
        public List<ValidationResult> ValidationResults { private set; get; } = new List<ValidationResult>();

        /// <summary>
        /// Validates the object according to the annotations assigned by the SQL Plus tags.
        /// When the method returns false the ValidationErrors will have a count > 1.
        /// </summary>
        /// <returns>True|False based on the valid state of the object.</returns>
        public virtual bool IsValid()
        {
            ClearErrors();
            Validator.TryValidateObject(this, new ValidationContext(this), ValidationResults, true);
            return ValidationResults.Count == 0;
        }

        /// <summary>
        /// Clears ValidationResults of any previous errors.
        /// </summary>
        public virtual void ClearErrors()
        {
            ValidationResults.Clear();
        }

        #endregion ValidInput

    }
}