// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerInsert
//     Last Modified On: 4/30/2023 6:22:59 PM
//     Written By: Alan Hyneman
//     Select Type: NonQuery
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace FirstService.dbo.Models
{
    /// <summary>
    /// Output object for CustomerInsert service.
    /// </summary>
    public partial class CustomerInsertOutput
    {

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        public int? CustomerId { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Actual return value for the routine.
        /// </summary>
        public int? ReturnValue { set; get; }

        #endregion Return Value
    }









}
