// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerInsert
//     Last Modified On: 4/30/2023 6:22:59 PM
//     Written By: Alan Hyneman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace FirstService.dbo.Models
{
    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerInsert service.
    /// </summary>
    public partial class CustomerInsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerInsertInput.
        /// </summary>
        public CustomerInsertInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerInsertInput.
        /// </summary>
        /// <param name="CustomerTypeId">Maps to parameter @CustomerTypeId.</param>
        /// <param name="FirstName">Maps to parameter @FirstName.</param>
        /// <param name="LastName">Maps to parameter @LastName.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        public CustomerInsertInput(byte? CustomerTypeId, string FirstName, string LastName, string Email)
        {
            this.CustomerTypeId = CustomerTypeId;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Email = Email;
        }

        #endregion Constructors

        #region Fields

        private byte? _CustomerTypeId;
        /// <summary>
        /// Maps to parameter @CustomerTypeId.
        /// </summary>
        public byte? CustomerTypeId
        {
            get => _CustomerTypeId;
            set => _CustomerTypeId = value;
        }

        private string _FirstName;
        /// <summary>
        /// Maps to parameter @FirstName.
        /// </summary>
        public string FirstName
        {
            get => _FirstName;
            set => _FirstName = value;
        }

        private string _LastName;
        /// <summary>
        /// Maps to parameter @LastName.
        /// </summary>
        public string LastName
        {
            get => _LastName;
            set => _LastName = value;
        }

        private string _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        public string Email
        {
            get => _Email;
            set => _Email = value;
        }

        #endregion

    }
}