// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerDelete
//     Last Modified On: 3/15/2023 7:56:24 PM
//     Written By: Alan@SQLPlus.net
//     Select Type: NonQuery
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Bad.Models
{
    #nullable enable

    /// <summary>
    /// Output object for CustomerDelete service.
    /// </summary>
    public partial class CustomerDeleteOutput
    {

        #region Return Value

        /// <summary>
        /// Actual return value for the routine.
        /// </summary>
        public int? ReturnValue { set; get; }

        #endregion Return Value
    }









}
