// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSave
//     Last Modified On: 3/15/2023 7:34:35 PM
//     Written By: alan@sqlplus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Best.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerSave service.
    /// </summary>
    public partial class CustomerSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerSaveInput.
        /// </summary>
        public CustomerSaveInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerSaveInput.
        /// </summary>
        /// <param name="CustomerId">Set to 0 for an insert, otherwise provide the customer id</param>
        /// <param name="LastName">Maps to parameter @LastName.</param>
        /// <param name="FirstName">Maps to parameter @FirstName.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        public CustomerSaveInput(int? CustomerId, string? LastName, string? FirstName, string? Email)
        {
            this.CustomerId = CustomerId;
            this.LastName = LastName;
            this.FirstName = FirstName;
            this.Email = Email;
        }

        #endregion Constructors

        #region Fields

        private int? _CustomerId = 0;
        /// <summary>
        /// Set to 0 for an insert, otherwise provide the customer id
        /// </summary>
        [Required]
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private string? _LastName;
        /// <summary>
        /// Maps to parameter @LastName.
        /// </summary>
        [MaxLength(64)]
        [Required]
        [Display(Name = "Last Name", Description = "Description")]
        public string? LastName
        {
            get => _LastName;
            set => _LastName = value;
        }

        private string? _FirstName;
        /// <summary>
        /// Maps to parameter @FirstName.
        /// </summary>
        [MaxLength(64)]
        [Required]
        [Display(Name = "First Name", Description = "Description")]
        public string? FirstName
        {
            get => _FirstName;
            set => _FirstName = value;
        }

        private string? _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        [MaxLength(64)]
        [Required]
        [EmailAddress]
        public string? Email
        {
            get => _Email;
            set => _Email = value;
        }

        #endregion

    }
}