// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SQLPlus.net for more information on SQL PLUS.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SqlPlusBase
{
    #region usings

    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Data;

    #endregion

    
    /// <summary>
    /// Example of retry options targeting AzureSql with retry intervals of 1, 2, and 5 seconds.
    /// Note this is for illustration only.
    /// Your actually implementation should suit the needs or your application.
    /// </summary>
    public class SampleRetryOptions : RetryOptions
    {
        /// <summary>
        /// Constructor for the SampleRetryOptions
        /// </summary>
        public SampleRetryOptions() :
            base(
                new List<int> { 2, 4060, 40197, 40501, 40613, 49918, 49919, 49920, 11001 },
                new List<int> { 1000, 2000, 5000 },
                new TransientConsoleLogger()
                )
        { }
    }


    /// <summary>
    /// ITransientLogger implementation for writing to the console.
    /// Note this is for illustration only.
    /// Your actually implementation should suit the needs or your application.
    /// </summary>
    public class TransientConsoleLogger : ITransientLogger
    {
        /// <summary>
        /// Logs the exception
        /// </summary>
        /// <param name="sqlException">The exception to log</param>
        public void Log(SqlException sqlException)
        {
            try
            {
                Console.Write($"SQL Exception: Error Number: {sqlException.Number}, LineNumber: {sqlException.LineNumber}, Message: {sqlException.Message}");
            }
            catch { }
        }
    }
}

