// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SqlPlusBase
{
    #region usings

    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Data;

    #endregion

    #region Transient Logger

    /// <summary>
    /// Implementation of this interface is utilized for any transient error logging.
    /// </summary>
    public interface ITransientLogger
    {
        /// <summary>
        /// Logs the exception.
        /// </summary>
        /// <param name="sqlException">The exception to log.</param>
        void Log(SqlException sqlException);
    }

    #endregion Transient Logger

    #region Retry Options

    /// <summary>
    /// Implementation of this interface is utilized for handling any transient errors.
    /// </summary>
    public interface IRetryOptions
    {
        /// <summary>
        /// List of error numbers to treat as transient.
        /// </summary>
        List<int> TransientErrorNumbers { get; }

        /// <summary>
        /// List of Retry Intervals in milliseconds.
        /// </summary>
        List<int> RetryIntervals { get; }

        /// <summary>
        /// Implentation of ITransientLogger.
        /// </summary>
        ITransientLogger Logger { get; }
    }

    /// <summary>
    /// Base class for retry options. Non transaction instantiation of the service component takes an optional parameter for retry options.
    /// When no options are explicitly passed the NoRetryOptions are utilized.
    /// </summary>
    public abstract class RetryOptions : IRetryOptions
    {
        /// <summary>
        /// Constructor for the RetryOptions.
        /// </summary>
        /// <param name="transientErrorNumbers">List of error numbers to treat as transient.</param>
        /// <param name="retryIntervals">List of Retry Intervals in milliseconds.</param>
        /// <param name="logger">Implentation of ITransientLogger. Leave null to exclude logging is bypassed.</param>
        public RetryOptions (List<int> transientErrorNumbers, List<int> retryIntervals, ITransientLogger logger)
        {
            if (transientErrorNumbers == null)
            {
                throw new ArgumentNullException("transientErrorNumbers", "Value cannot be null");
            }

            if (retryIntervals == null)
            {
                throw new ArgumentNullException("retryIntervals", "Value cannot be null");
            }

            TransientErrorNumbers = transientErrorNumbers;
            RetryIntervals = retryIntervals;
            Logger = logger;
        }

        /// <summary>
        /// List of error numbers to treat as transient.
        /// </summary>
        public List<int> TransientErrorNumbers { private set; get; }

        /// <summary>
        /// List of Retry Intervals in milliseconds.
        /// </summary>
        public List<int> RetryIntervals { private set; get; }

        /// <summary>
        /// Implentation of ITransientLogger.
        /// </summary>
        public ITransientLogger Logger { private set; get; }

    }

    #endregion Retry Options
}
