// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSave_V1
//     Last Modified On: 4/3/2023 1:20:44 PM
//     Written By: alan@sqlplus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default
{
    #nullable enable

    #region Using Statments

    using GettingStarted.DataServices.Default.Models;
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the CustomerSave_V1 routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand CustomerSave_V1_BuildCommand(SqlConnection cnn, CustomerSave_V1Input input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[CustomerSave_V1]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CustomerId",
                Direction = ParameterDirection.InputOutput,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CustomerTypeId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.TinyInt,
                Scale = 0,
                Precision = 3,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@FirstName",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 64,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LastName",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.NVarChar,
                Size = 64,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Email",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 256,
                Value = DBNull.Value
            });

            if (input.CustomerId != null)
            {
                result.Parameters["@CustomerId"].Value = input.CustomerId;
            }
            if (input.CustomerTypeId != null)
            {
                result.Parameters["@CustomerTypeId"].Value = input.CustomerTypeId;
            }
            if (input.FirstName != null)
            {
                result.Parameters["@FirstName"].Value = input.FirstName;
            }
            if (input.LastName != null)
            {
                result.Parameters["@LastName"].Value = input.LastName;
            }
            if (input.Email != null)
            {
                result.Parameters["@Email"].Value = input.Email;
            }
            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void CustomerSave_V1_SetParameters(SqlCommand cmd, CustomerSave_V1Output output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (int?)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.CustomerId = (int?)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Execute Command

        private void CustomerSave_V1_Execute(SqlCommand cmd, CustomerSave_V1Output output)
        {
            cmd.ExecuteNonQuery();

            CustomerSave_V1_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Public Service

        /// <summary>
        /// Inserts or updates the customer based on the value of the customer id.<br/>
        /// DB Routine: dbo.CustomerSave_V1<br/>
        /// Author: alan@sqlplus.net<br/>
        /// </summary>
        /// <param name="input">CustomerSave_V1Input instance.</param>
        /// <returns>Instance of CustomerSave_V1Output</returns>
        public CustomerSave_V1Output CustomerSave_V1(CustomerSave_V1Input input)
        {
            ValidateInput(input, nameof(CustomerSave_V1));
            CustomerSave_V1Output output = new CustomerSave_V1Output();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = CustomerSave_V1_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    CustomerSave_V1_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = CustomerSave_V1_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						CustomerSave_V1_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

