// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSelect
//     Last Modified On: 5/1/2023 1:25:39 AM
//     Written By: alan@sqlplus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default
{
    #nullable enable

    #region Using Statments

    using GettingStarted.DataServices.Default.Models;
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the CustomerSelect routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand CustomerSelect_BuildCommand(SqlConnection cnn, CustomerSelectInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[CustomerSelect]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CustomerId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.CustomerId
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void CustomerSelect_SetParameters(SqlCommand cmd, CustomerSelectOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (CustomerSelectOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private CustomerSelectResult CustomerSelect_ResultData(SqlDataReader rdr)
        {
            return new CustomerSelectResult(
            rdr.GetInt32(0),
            rdr.GetByte(1),
            rdr.GetString(2),
            rdr.GetString(3),
            rdr.GetString(4)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void CustomerSelect_Execute(SqlCommand cmd, CustomerSelectOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = CustomerSelect_ResultData(rdr);
                }
                rdr.Close();
            }

            CustomerSelect_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Public Service

        /// <summary>
        /// Selects customer for the given CustomerId.<br/>
        /// DB Routine: dbo.CustomerSelect<br/>
        /// Author: alan@sqlplus.net<br/>
        /// </summary>
        /// <param name="input">CustomerSelectInput instance.</param>
        /// <returns>Instance of CustomerSelectOutput</returns>
        public CustomerSelectOutput CustomerSelect(CustomerSelectInput input)
        {
            ValidateInput(input, nameof(CustomerSelect));
            CustomerSelectOutput output = new CustomerSelectOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = CustomerSelect_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    CustomerSelect_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = CustomerSelect_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						CustomerSelect_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

