// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: Customers
//     Last Modified On: 3/15/2023 7:52:27 PM
//     Written By: Alan@SQLPlus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Best
{
    #nullable enable

    #region Using Statments

    using GettingStarted.DataServices.Best.Models;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the Customers routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand Customers_BuildCommand(SqlConnection cnn, CustomersInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[best].[Customers]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PageSize",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.PageSize
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PageNumber",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.PageNumber
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PageCount",
                Direction = ParameterDirection.Output,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void Customers_SetParameters(SqlCommand cmd, CustomersOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (CustomersOutput.Returns)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[3].Value != DBNull.Value)
            {
                output.PageCount = (int?)cmd.Parameters[3].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private CustomersResult Customers_ResultData(SqlDataReader rdr)
        {
            return new CustomersResult(
            rdr.GetInt32(0),
            rdr.GetString(1),
            rdr.GetString(2),
            rdr.GetString(3)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void Customers_Execute(SqlCommand cmd, CustomersOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<CustomersResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(Customers_ResultData(rdr));
                }
                rdr.Close();
            }

            Customers_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Public Service

        /// <summary>
        /// Gets all customers, parameter validation, default values, return values.<br/>
        /// DB Routine: best.Customers<br/>
        /// Author: Alan@SQLPlus.net<br/>
        /// </summary>
        /// <param name="input">CustomersInput instance.</param>
        /// <returns>Instance of CustomersOutput</returns>
        public CustomersOutput Customers(CustomersInput input)
        {
            ValidateInput(input, nameof(Customers));
            CustomersOutput output = new CustomersOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = Customers_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    Customers_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = Customers_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						Customers_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

