// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSave_V1
//     Last Modified On: 4/3/2023 1:20:44 PM
//     Written By: alan@sqlplus.net
//     Select Type: NonQuery
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default.Models
{
    #nullable enable

    /// <summary>
    /// Output object for CustomerSave_V1 service.
    /// </summary>
    public partial class CustomerSave_V1Output
    {

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        public int? CustomerId { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Actual return value for the routine.
        /// </summary>
        public int? ReturnValue { set; get; }

        #endregion Return Value
    }









}
