// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSave
//     Last Modified On: 5/6/2023 3:06:52 PM
//     Written By: alan@sqlplus.net
//     Select Type: NonQuery
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default.Models
{
    #nullable enable

    /// <summary>
    /// Output object for CustomerSave service.
    /// </summary>
    public partial class CustomerSaveOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// New customer added
            /// </summary>
             Inserted = 1,
            /// <summary>
            /// No customer found for the given id
            /// </summary>
             NotFound = 101,
            /// <summary>
            /// Customer record was modified
            /// </summary>
             Modified = 2,
            /// <summary>
            /// Cannot insert duplicate email
            /// </summary>
             Duplicate = 102,
            /// <summary>
            /// Not a valid Customer Type
            /// </summary>
             ForeignKeyViolation = 103
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Set to 0 for an insert, existing customer id for an update
        /// </summary>
        public int? CustomerId { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value
    }









}
