// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSelect
//     Last Modified On: 3/27/2023 10:14:55 PM
//     Written By: alan@sqlplus.net
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default.Models
{
    #nullable enable

    /// <summary>
    /// Output object for CustomerSelect service.
    /// </summary>
    public partial class CustomerSelectOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// No customer found for the given id
            /// </summary>
             NotFound = 101,
            /// <summary>
            /// Customer retrieved
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of CustomerSelectResult.
        /// </summary>
        public CustomerSelectResult? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for CustomerSelect service.
    /// </summary>




    public partial class CustomerSelectResult
	{
        /// <summary>
        /// Result set object for CustomerSelect.
        /// </summary>
        /// <param name="CustomerId">Maps to table value column CustomerId.</param>
        /// <param name="CustomerTypeId">Maps to table value column CustomerTypeId.</param>
        /// <param name="FirstName">Maps to table value column FirstName.</param>
        /// <param name="LastName">Maps to table value column LastName.</param>
        /// <param name="Email">Maps to table value column Email.</param>
        public CustomerSelectResult(int CustomerId, byte CustomerTypeId, string FirstName, string LastName, string Email)
        {
             this.CustomerId = CustomerId;
             this.CustomerTypeId = CustomerTypeId;
             this.FirstName = FirstName;
             this.LastName = LastName;
             this.Email = Email;
        }


        /// <summary>
        /// Maps to table value column CustomerId.
        /// </summary>
        public int CustomerId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerTypeId.
        /// </summary>
        public byte CustomerTypeId { set; get; }

        /// <summary>
        /// Maps to table value column FirstName.
        /// </summary>
        public string FirstName { set; get; }

        /// <summary>
        /// Maps to table value column LastName.
        /// </summary>
        public string LastName { set; get; }

        /// <summary>
        /// Maps to table value column Email.
        /// </summary>
        public string Email { set; get; }
    }


    #endregion Result Set Objects

}
