// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: Customers
//     Last Modified On: 3/25/2023 3:28:44 PM
//     Written By: alan@sqlplus.net
//     Select Type: MultiRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default.Models
{
    #nullable enable


    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for Customers service.
    /// </summary>
    public partial class CustomersOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NoRecords
            /// </summary>
             NoRecords = 101,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Returns the number of pages available
        /// </summary>
        public int? PageCount { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of CustomersResult.
        /// </summary>
        public List<CustomersResult>? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for Customers service.
    /// </summary>




    public partial class CustomersResult
	{
        /// <summary>
        /// Result set object for Customers.
        /// </summary>
        /// <param name="CustomerId">Maps to table value column CustomerId.</param>
        /// <param name="CustomerTypeId">Maps to table value column CustomerTypeId.</param>
        /// <param name="FirstName">Maps to table value column FirstName.</param>
        /// <param name="LastName">Maps to table value column LastName.</param>
        /// <param name="Email">Maps to table value column Email.</param>
        public CustomersResult(int CustomerId, byte CustomerTypeId, string FirstName, string LastName, string Email)
        {
             this.CustomerId = CustomerId;
             this.CustomerTypeId = CustomerTypeId;
             this.FirstName = FirstName;
             this.LastName = LastName;
             this.Email = Email;
        }


        /// <summary>
        /// Maps to table value column CustomerId.
        /// </summary>
        public int CustomerId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerTypeId.
        /// </summary>
        public byte CustomerTypeId { set; get; }

        /// <summary>
        /// Maps to table value column FirstName.
        /// </summary>
        public string FirstName { set; get; }

        /// <summary>
        /// Maps to table value column LastName.
        /// </summary>
        public string LastName { set; get; }

        /// <summary>
        /// Maps to table value column Email.
        /// </summary>
        public string Email { set; get; }
    }


    #endregion Result Set Objects

}
