// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerSave_V2
//     Last Modified On: 5/1/2023 1:25:39 AM
//     Written By: alan@sqlplus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Default.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerSave_V2 service.
    /// </summary>
    public partial class CustomerSave_V2Input : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerSave_V2Input.
        /// </summary>
        public CustomerSave_V2Input() { }

        /// <summary>
        /// Parameterized constructor for CustomerSave_V2Input.
        /// </summary>
        /// <param name="CustomerId">Maps to parameter @CustomerId.</param>
        /// <param name="CustomerTypeId">Maps to parameter @CustomerTypeId.</param>
        /// <param name="FirstName">Maps to parameter @FirstName.</param>
        /// <param name="LastName">Maps to parameter @LastName.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        public CustomerSave_V2Input(int? CustomerId, byte? CustomerTypeId, string? FirstName, string? LastName, string? Email)
        {
            this.CustomerId = CustomerId;
            this.CustomerTypeId = CustomerTypeId;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Email = Email;
        }

        #endregion Constructors

        #region Fields

        private int? _CustomerId = 0;
        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        [Required]
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private byte? _CustomerTypeId;
        /// <summary>
        /// Maps to parameter @CustomerTypeId.
        /// </summary>
        [Required]
        public byte? CustomerTypeId
        {
            get => _CustomerTypeId;
            set => _CustomerTypeId = value;
        }

        private string? _FirstName;
        /// <summary>
        /// Maps to parameter @FirstName.
        /// </summary>
        [MaxLength(64)]
        [Required]
        public string? FirstName
        {
            get => _FirstName;
            set => _FirstName = value;
        }

        private string? _LastName;
        /// <summary>
        /// Maps to parameter @LastName.
        /// </summary>
        [MaxLength(64)]
        [Required]
        public string? LastName
        {
            get => _LastName;
            set => _LastName = value;
        }

        private string? _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        [MaxLength(256)]
        [Required]
        [EmailAddress]
        public string? Email
        {
            get => _Email;
            set => _Email = value;
        }

        #endregion

    }
}