// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SQLplus.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Enumerations
{
    /// <summary>
    /// Enumeration for query AddressType
    /// </summary>
    public enum AddressType : System.Byte
    {
        /// <summary>
        /// Residential Address
        /// </summary>
        Residential = 1,

        /// <summary>
        /// Business Address
        /// </summary>
        Business = 2

    }
}
