// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerDelete
//     Last Modified On: 3/15/2023 7:56:24 PM
//     Written By: Alan@SQLPlus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Bad.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerDelete service.
    /// </summary>
    public partial class CustomerDeleteInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerDeleteInput.
        /// </summary>
        public CustomerDeleteInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerDeleteInput.
        /// </summary>
        /// <param name="CustomerId">Maps to parameter @CustomerId.</param>
        public CustomerDeleteInput(int? CustomerId)
        {
            this.CustomerId = CustomerId;
        }

        #endregion Constructors

        #region Fields

        private int? _CustomerId;
        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        #endregion

    }
}