// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerUpdate
//     Last Modified On: 2/28/2023 5:42:00 PM
//     Written By: Alan@SQLPlus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Good.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerUpdate service.
    /// </summary>
    public partial class CustomerUpdateInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerUpdateInput.
        /// </summary>
        public CustomerUpdateInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerUpdateInput.
        /// </summary>
        /// <param name="CustomerId">Maps to parameter @CustomerId.</param>
        /// <param name="FirstName">Maps to parameter @FirstName.</param>
        /// <param name="LastName">Maps to parameter @LastName.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        public CustomerUpdateInput(int? CustomerId, string? FirstName, string? LastName, string? Email)
        {
            this.CustomerId = CustomerId;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Email = Email;
        }

        #endregion Constructors

        #region Fields

        private int? _CustomerId;
        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private string? _FirstName;
        /// <summary>
        /// Maps to parameter @FirstName.
        /// </summary>
        public string? FirstName
        {
            get => _FirstName;
            set => _FirstName = value;
        }

        private string? _LastName;
        /// <summary>
        /// Maps to parameter @LastName.
        /// </summary>
        public string? LastName
        {
            get => _LastName;
            set => _LastName = value;
        }

        private string? _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        public string? Email
        {
            get => _Email;
            set => _Email = value;
        }

        #endregion

    }
}