// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: HelloWorld
//     Last Modified On: 3/24/2023 12:34:58 AM
//     Written By: Alan@SQLPlus.net
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Samples.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the HelloWorld service.
    /// </summary>
    public partial class HelloWorldInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for HelloWorldInput.
        /// </summary>
        public HelloWorldInput() { }

        /// <summary>
        /// Parameterized constructor for HelloWorldInput.
        /// </summary>
        /// <param name="Name">Maps to parameter @Name.</param>
        public HelloWorldInput(string? Name)
        {
            this.Name = Name;
        }

        #endregion Constructors

        #region Fields

        private string? _Name;
        /// <summary>
        /// Maps to parameter @Name.
        /// </summary>
        [Required]
        [MaxLength(32)]
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        #endregion

    }
}