// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: HelloWorld
//     Last Modified On: 3/24/2023 12:34:58 AM
//     Written By: Alan@SQLPlus.net
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace GettingStarted.DataServices.Samples.Models
{
    #nullable enable

    /// <summary>
    /// Output object for HelloWorld service.
    /// </summary>
    public partial class HelloWorldOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @ReturnValue.
        /// </summary>
        public Returns? ReturnValue { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// Single instance of HelloWorldResult.
        /// </summary>
        public HelloWorldResult? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for HelloWorld service.
    /// </summary>




    public partial class HelloWorldResult
	{
        /// <summary>
        /// Result set object for HelloWorld.
        /// </summary>
        /// <param name="WelcomMessage">Maps to table value column WelcomMessage.</param>
        public HelloWorldResult(string WelcomMessage)
        {
             this.WelcomMessage = WelcomMessage;
        }


        /// <summary>
        /// Maps to table value column WelcomMessage.
        /// </summary>
        public string WelcomMessage { set; get; }
    }


    #endregion Result Set Objects

}
